version: "3.4"
services:
  origin:
    build: docker/apache-origin-cmsd
    container_name: origin
    networks:
      - origin-cmsd-net
    ports:
      - 8080:80
    environment:
      - LOG_LEVEL=warn
    volumes:
    - ./static-media/:/var/www/origin/
    - ./docker/apache-origin-cmsd/conf.d/:/etc/apache2/conf.d/ 
    - ./docker/apache-origin-cmsd/lua/:/var/www/lua/
  # **************** Origin shield proxy (Nginx)  ****************
  nginx-njs:
    build: docker/nginx
    container_name: nginx-njs
    networks:
      - origin-cmsd-net
    ports:
      - 8081:80
    depends_on:
      - origin
    environment:
      - TARGET=origin
      - LOG_LEVEL=warn
    volumes:
      - ./docker/nginx/njs/:/etc/nginx/njs/:ro
    command: [nginx-debug, '-g', 'daemon off;']
  # **************** Varnish cache  ****************
  varnish-cache:
    build: docker/varnish
    container_name: varnish-cache
    networks:
      - origin-cmsd-net
    ports: 
      - 80:80
    depends_on:
      - nginx-njs
    environment:
      - TARGET_HOST=nginx-njs
      - TARGET_PORT=80

networks:
  origin-cmsd-net:
    driver: bridge
